### ISSUE TITLE
Target only one monitor

### ISSUE THREAD

**Issue by JonathanGrant** [tomtaylor/satellite-eyes#69] opened 2018-09-18 16:13 UTC
I have three monitors. I only want this to target one monitor.

**Comment by hugovk** [comment] 2018-12-19 15:41
This is a duplicate of https://github.com/tomtaylor/satellite-eyes/issues/64.

**Comment by tomtaylor** [comment] 2019-10-17 07:31
Thanks @JonathanGrant - closing as a dupe of #64

**Closed by tomtaylor** 2019-10-17 07:31 UTC
